services:
  mysql:
    platform: linux/x86_64 # m1 mac 이슈
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./mysql:/var/lib/mysql